=== EatZeBaby/M2SITN/recherche_et_gestion_web/tp/TD7/util.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:annotation>
        <xs:documentation>Ce type permet de tester tous les types d'éléments définis dans ce schéma:
        DateType_F, LieuNameType, TelephoneType, VoieType, NaissanceType, CodeType, NumeroType, AdresseType</xs:documentation>
    </xs:annotation>
    <xs:element name="testUtil" >
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="lieu" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="ville" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="pays" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="code" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="voie" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="numero"  minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="naissance" type="NaissanceType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="telephone" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="adresse" minOccurs="0" maxOccurs="unbounded"/>
            
            </xs:choice>
        </xs:complexType>
        
    </xs:element>

    <!-- Définition des éléments de base --> 
<xs:element name="date" type="DateType_F"/>
<xs:element name="lieu" >
<xs:complexType >
	<xs:group ref="LieuGroup"/>
	</xs:complexType>
</xs:element>
	
		
<xs:element name="ville" type="LieuNameType"/>
<xs:element name="pays" type="LieuNameType"/>
<xs:element name="code" type="CodeType"/>
<xs:element name="voie" type="VoieType"/>
<xs:element name="numero" type="NumeroType"/>
<xs:element name="telephone" type="TelephoneType"/>
<xs:element name="adresse" type="AdresseType"/>

<!-- Comprend des types utilisés ultérieurement pour décrire des personnes auteurs emprunteurs employés.
    NaissanceType
    DateType_F
    LieuType
    -->
<xs:complexType name="NaissanceType" mixed="true">
	<xs:sequence minOccurs="0" maxOccurs="1">
	<xs:element ref="date" />
	<xs:element ref="lieu" />
	</xs:sequence>
</xs:complexType>

<!--Format français des dates jour/mois/siècleAnnée prenant des dates de 1600 à 2012
	Ce format pouvant être utilisé ultérieurement pour les auteurs et leur biographie, 
	j'étends l'intervalle de définition à 1600.
	 Ici sont prises en compte les dates comprises entre 01/01/1600 et 31/12/2012. 
	 C’est un type dérivé de token.
         <xs:pattern 

	-->
<xs:simpleType name="DateType_F">
<xs:restriction base="xs:token">
    <!--mois de février -->
<xs:pattern 
    value="(0[1-9]|[12][0-9])/02/(1[6-9][0-9]{2}|200[0-9]|201[0-4])"/>
<!-- mois à 30 jours -->
<xs:pattern 
    value="(0[1-9]|[12][0-9]|30)/((0(4|6|9))|11)/(1[6-9][0-9]{2}|200[0-9]|201[0-4])"/>
<!-- mois à 31 jours -->
<xs:pattern 
    value="(0[1-9]|[12][0-9]|(30|31))/((0(1|3|5|7|8))|(10|12))/(1[6-9][0-9]{2}|200[0-9]|201[0-4])"/>
</xs:restriction>
</xs:simpleType>

<!-- LieuType caractérise une ville, un pays un lieu de naissance, 
	c'est une chaîne de caractères normalisée 
	d’au moins 2 caractères et pouvant comporter de 1 à 4 mots.
Exemples : Paris, Lo, Villeneuve sur lot, Saint Faust du haut, France
  -->
<xs:simpleType name="LieuNameType">
	<xs:restriction base="xs:normalizedString">
		<xs:pattern value="\p{L}+(\s(\p{L})+){0,3}"/>
		<xs:minLength value="2"/>

	</xs:restriction>
</xs:simpleType>


	
	<!-- groupement utilisé dans LieuType et AdresseType utilisé
pour la naissance d'une personne et non l'adresse du domicile -->
<!-- type utilisé pour la naissance d'une personne et non l'adresse 
du domicile -->
	<xs:complexType name="LieuType">
    <xs:group ref="LieuGroup" minOccurs="1" maxOccurs="1"/>
   </xs:complexType>
	
	<xs:group name="LieuGroup">
		<xs:sequence>
		 <xs:element ref="ville" minOccurs="1" maxOccurs="1"/>
       <xs:element ref="pays" minOccurs="0" maxOccurs="1"/>
     </xs:sequence>
    </xs:group>

        
<!-- telephone
		caractérise les numéros de téléphones suivant la nomenclature 
                française 
		qui peuvent commencer 
		par 01, 02, 03,04, 05, 06, 09, 08, 07. 
		l’international est également pris en compte.
		exemples: 0625305967 ou 0033147607890 ou +33147607890
		-->
    <xs:simpleType name="TelephoneType">
      <xs:restriction base="xs:token">
        <xs:pattern value="0[1-9]{2}[0-9]{7}"/>
        <!--<xs:pattern value="0033[1-9][1-9][0-9]{7}"/>
        <xs:pattern value="+33[1-9][1-9][0-9]{7}"/>-->
      </xs:restriction>
    </xs:simpleType>


<!-- 
	le code postal est un nombre de 5 caractères allant de 01000 à 98999
	exemple : 01000 BOURG EN BRESSE,  98890 PAITA, 
	988 représentant le code de la Nouvelle Calédonie
	01 Ain ... 95 Val d Oise
	971 Guadeloupe 972 Martinique 973 Guyane 974 Reunion
	975 St-Pierre-et-Miquelon 976 Mayotte
	986 Wallis et Futuna 987 Polynesie Francaise 988 Nouvelle-Caledonie
	-->
<xs:simpleType name="CodeType" >
<xs:restriction base="xs:integer">
<xs:minInclusive value="01000"/>
<xs:pattern value="[0-8][0-9]\d{3}|9[0-5]\d{3}|97[1-6]\d{2}|98[6-8]\d{2}"/>
</xs:restriction>
</xs:simpleType>

<!-- NumeroType est un type simple compris entre [1,9999]-->
<xs:simpleType name="NumeroType" >
<xs:restriction base="xs:integer">
<xs:minInclusive value="1"/>
<xs:pattern value="[1-9]\d{0,3}"/>
</xs:restriction>
</xs:simpleType>

<!-- 2.	La voie est de type VoieType qui est un type simple 
	commençant par un des mots  rue ou avenue ou impasse ou boulevard 
	suivi du nom de la voir qui est défini par au minimum un mot et au maximum 4 mots.
Exemples : rue Lamartine, boulevard De Lattre De Tassigny.
	-->
<xs:simpleType name="VoieType2" >
  <xs:restriction base="xs:normalizedString">
    <xs:pattern value="(rue|avenue|impasse|boulevard|place)\s\p{L}+(\s(\p{L})+){0,3}"/>
  </xs:restriction>
</xs:simpleType>


<xs:complexType name="AdresseType">
	<xs:sequence minOccurs="1" maxOccurs="5">
		<xs:element ref="numero" minOccurs="0" maxOccurs="1"/>
		<xs:element ref="voie" minOccurs="0" maxOccurs="1"/>
		<xs:element ref="code" minOccurs="0" maxOccurs="1"/>
		<xs:group ref="LieuGroup"/>
	</xs:sequence>
</xs:complexType>

<xs:simpleType name="NssType">
        <xs:restriction base="xs:normalizedString">
            <xs:pattern value="[1-2](\s)?\d{2}(\s)?(0[1-9]|1[0-2])(\s)?(\d[1-9]|2(A|B))(\s)?((0\d[1-9])|([1-9]\d{2}))(\s)?\d{3}(\s)?\d{2}" />
        </xs:restriction>
    </xs:simpleType>

<xs:simpleType name="VoieType" >
  <xs:union memberTypes="VoieIndentType LieuNameType"/>
</xs:simpleType>

<xs:simpleType name="VoieIndentType">
   <xs:restriction base="xs:NMTOKEN">
       <xs:enumeration value="rue "/>
       <xs:enumeration value="avenue "/>
           <xs:enumeration value="impasse "/>
    <xs:enumeration value="boulevard "/>
     <xs:enumeration value="place "/>
      <xs:enumeration value="Rue "/>
       <xs:enumeration value="Avenue "/>
           <xs:enumeration value="Impasse "/>
    <xs:enumeration value="Boulevard "/>
     <xs:enumeration value="Place "/>
   </xs:restriction>
</xs:simpleType>

</xs:schema>

=== EatZeBaby/M2SITN/recherche_et_gestion_web/tp/TD7/testUtil2.xml
<testUtil xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="util.xsd">
	
    
	<!-- vérifie le domaine de définition sur les dates 
		erreurs 26/13/1780, 35/02/1900 30/01/2013 31/12/1590 30/02/2012-->
	 <!--Format français des dates jour/mois/siècleAnnée prenant des dates de 1600 à 2012
	Ce format pouvant être utilisé ultérieurement pour les auteurs et leur biographie, 
	j'étends l'intervalle de définition à 1600.
	 Ici sont prises en compte les dates comprises entre 01/01/1600 et 31/12/2012. 
	 C’est un type dérivé de token.
	-->
	 <date>01/01/1600</date><date>29/02/2012</date> <date>31/01/1900</date>
 <!-- vérifie le domaine sur les villes pays 
 	erreur : nom de ville superieure a quatre,espagne1 -->
<ville>Villeurbanne</ville> <ville>Villeneuve sur lot</ville><ville>Po</ville> 
<ville>Saint Faust du haut</ville> 
<pays>France</pays> <pays>Coree du sud</pays>

<!-- vérifie les différentes formes d'un lieu : soit juste une ville soit une ville et un pays 
	erreur: <lieu><pays>France</pays></lieu>, -->
<lieu>
<ville>Saint Faust du haut</ville></lieu>
<lieu><ville>Villeurbanne</ville><pays>France</pays></lieu>

<!-- vérifie les différentes formes d'un numéro téléphonique -->
<telephone>0625305967</telephone> <telephone>0925305967</telephone><telephone>0125305967</telephone><telephone>033147607890</telephone>

<!-- vérifie le code postal d'un lieu français
	le code postal est un nombre de 5 caractères allant de 01000 à 98999
	exemple : 01000 BOURG EN BRESSE,  98890 PAITA, 
	988 représentant le code de la Nouvelle Calédonie
	01 Ain ... 95 Val d Oise
	971 Guadeloupe 972 Martinique 973 Guyane 974 Reunion
	975 St-Pierre-et-Miquelon 976 Mayotte
	986 Wallis et Futuna 987 Polynesie Francaise 988 Nouvelle-Caledonie
	Erreurs:00987, 100987, 96578
	-->
	<code>01000</code><code>98890</code><code>75098</code><code>97578</code>
	<!-- vérifie les informations liées à la voie, c'est à dire le type VoieType qui est un type simple 
	commençant par un des mots  rue ou avenue ou impasse ou boulevard 
	suivi du nom de la voie qui est défini par au minimum un mot et au maximum 4 mots.
Exemples : rue Lamartine, boulevard De Lattre De Tassigny.-->

<voie>impasse du four</voie> <voie>boulevard du crepuscule</voie><voie>rue Lamartine</voie><voie>avenue Lannes</voie>
 <voie>boulevard de Lattre de Tassigny</voie>

<!-- vérifie le format associé à une adresse -->
<adresse>
	<numero>178</numero>
	<voie>boulevard du crepuscule</voie>
	<code>75011</code>
	<ville>Paris</ville>
	<pays>France</pays>
</adresse>
</testUtil>
